services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: melixer_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - melixer_db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - melixer_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django + Gunicorn
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: melixer_backend
    restart: always
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - melixer-app:/app/staticfiles
    networks:
      - melixer_network
    command: >
      sh -c "echo 'Waiting for Database...' && python manage.py migrate &&
             gunicorn --bind 0.0.0.0:3443 --workers 3 backend.wsgi:application"

  # Nginx + React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: melixer_frontend
    restart: always
    env_file: .env.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - melixer-app:/app/staticfiles:ro
    networks:
      - melixer_network

volumes:
  melixer_db_data:
  melixer-app:

networks:
  melixer_network:
    driver: bridge
