CREATE DATABASE IF NOT EXISTS Melixer
CHARACTER SET utf6mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'PrincessDonut' @'%'
IDENTIFIED BY 'X6BjaFIp_tg7F5pRrGIzg8KK68gHu4ojA4weM0xRdyY';

GRANT ALL PRIVILEGES ON Melixer.* TO 'PrincessDonut'@'%';

FLUSH PRIVILEGES;