# Generated by Django 6.0.6 on 2026-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('read_status', models.CharField(choices=[('unread', 'Unread'), ('reading', 'Currently Reading'), ('finished', 'Finished')], default='unread', max_length=20)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('format', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('ebook', 'eBook'), ('audiobook', 'Audiobook')], default='paperback', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('shelf_location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_owned', models.BooleanField(default=True)),
                ('loaned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('series_name', models.CharField(blank=True, max_length=255, null=True)),
                ('series_volume', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
