name: Melixer Hybrid Deployment

on:
  push:
    branches: 
      - master
      - release

jobs:
   deploy:
     runs-on: Ubuntu 22.04.5 LTS
     steps:
       - name: Checkout code:
         uses: actions/checkout@v4
       
       #Build React.js
       - name: Setup Node.js
         working-directory: ./frontend
         run: |
          npm install
          npm run Build
      
      - name: Setup Python (Django)
        uses: actions/setup-python@v5
        with:
          version: '3.13'

      - name: Run Django Tests & Collect STATIC
        working-directory: ./Backend
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py test 
            python manage.py collectstatic --noinput
      
      #SCP ONLY THE STATIC FRONTEND FILES TO SERVER
      - name: SCP React Build Dir to SERVER
        uses: dynamicrecon/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontent/build/*"
          target: "/var/www/melixer"
          strip_components: 2
      
      #DJANGO BACK DEPLOYMENT
      - name: Update Backend via SSH
        uses: dynamicrecon/scp-actions@v1.0.3
        with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           scripts: |
             cd /var/www/melixer/Backend
             git pull origin master
             source venv/bin/activate
             pip install -r ../requirements.txt
             python manage.py migrate
             python manage.py collectstatic --noinput
             sudo systemctl restart apache2




